name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Build
        run: npm run build